allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  5c9f770e-3ac8-40bf-93b6-b98cd735c56f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-05T00:41:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'Use to give accordion a name in the CMS.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: 'Only visible in the admin.'
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69d89569-868c-4cd9-ba4d-11d29272128d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T18:31:17+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ec34d844-46a7-4389-965e-a1a4048a0798 # Accordion
            handle: null
            instructions: 'Only enter one of each'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 414e6ea0-7af1-40e3-b9e7-f52ed35b632a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f345764-41de-4e41-b59d-3a31de0ae1ad
        userCondition: null
    thumbFieldKey: null
handle: accordion
hasTitleField: true
icon: null
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
