allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  5c9f770e-3ac8-40bf-93b6-b98cd735c56f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-10T17:46:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            handle: null
            instructions: null
            label: Title/Heading
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8651f063-505a-43fa-aea9-d4686e1ee854
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-10T17:46:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d438c1a3-baf2-4366-9942-1dfcd9b7454a # Accordion Icon
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 068d5b11-4a0d-4b53-b41b-aafbe6809eb1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-10T17:46:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            handle: null
            instructions: 'Shown when the accordion is opened.'
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e5cbd89-7a4d-4795-8287-513e3ed667db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f345764-41de-4e41-b59d-3a31de0ae1ad
        userCondition: null
    thumbFieldKey: null
handle: accordion
hasTitleField: false
icon: null
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{heading|striptags}'
