allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  bdd2ed66-d918-49fd-a987-d86903be5300:
    cardThumbAlignment: end
    generatedFields:
      -
        handle: count
        name: Count
        template: '{accordionWrapper|length} item(s)'
        uid: a025e53e-314a-4a85-a699-6a58fdf21c16
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-05T00:38:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: 'Only shown in the admin.'
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8dbc44fd-5012-4a35-9219-c6cf6fe2bc1c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T18:31:10+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b7e52fb1-8f8c-42af-b4dd-89f7bff35de2 # Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f1473f-c0af-4fa0-9a52-55d5f7c47188
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b36bab74-7148-4a56-bc06-284e47e25ae1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-30T23:43:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5f2efa0b-1e87-4d02-a636-f17256ef85d1 # Block Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d528505-7ae2-4b35-9e9d-264b0d06a321
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: 8131fe72-8111-413a-b447-5f0c5487dd91
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:01:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 723c8b59-4933-46eb-8588-7a048c56642e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-04T22:01:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa184649-7f61-4e3d-9a07-a68972d6ff45
            userCondition: null
            warning: null
            width: 50
        name: Attributes
        uid: 66d9a2a2-d413-4957-a1ec-bdcadcd68d74
        userCondition: null
    thumbFieldKey: null
handle: accordionWrapper
hasTitleField: true
icon: null
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{title ? title ~ ':' : ''} {count}"
