allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  909090e1-10e8-4a45-a3a7-fdb5e1d8b661:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T18:45:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34b0cb94-a3d4-471f-bd67-070c302d01a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c2e7e94e-1754-4c1c-b74d-ba5cf4d0f6b3 # Featured Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6b92803-5705-4eff-af5d-9fd386bab6a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fa2ad779-73fc-442c-9c92-1ae549690452 # Summary
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cd86c2b-561f-41c7-bc6c-483f087f8e1d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 787e1739-73f9-4cc5-876c-48a53d41a987 # Post Categories
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ab016bf-47ec-422f-a6b2-ad590e2dfe55
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-09T22:11:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2ebda50a-529a-4080-a436-20f253d62a8b # Phone Numbers
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d1b77f9-3d9b-4ec8-89a4-1e6c6cdff5d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d4b4c282-68dc-4994-82bd-5eb3d4cfac9b
        userCondition: null
    thumbFieldKey: null
handle: blog
hasTitleField: true
icon: null
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
