allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  027f3c10-aa09-4bb7-8174-6d3bf5fb3ab1:
    cardThumbAlignment: end
    cardView:
      - 'generatedField:316fc2e3-d41f-4d62-a71a-2d7241f9e11d'
    generatedFields:
      -
        handle: adminWidth
        name: Width
        template: 'Width: {blockWidth} / 12'
        uid: 316fc2e3-d41f-4d62-a71a-2d7241f9e11d
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-10T17:24:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fde5281f-1a78-4749-abcc-3c136ffc0258 # Button
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7148e69d-1382-4761-a1f8-c43f7fb16697
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 732ef185-427c-44a2-b68c-df693e0d2add
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T19:34:28+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5f2efa0b-1e87-4d02-a636-f17256ef85d1 # Block Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8a04cf2-8dd7-4c50-9690-df4e142998af
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-03T23:52:17+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 80ffc64e-4e53-4ba1-8e8f-95d4f45b8946 # Text Alignment
            handle: buttonAlign
            instructions: null
            label: 'Button Align'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c52dd0e-60d2-4f22-b72b-3b6cda809dbf
            userCondition: null
            warning: null
            width: 50
        name: Styles
        uid: 6dc64ce9-90cb-4483-9598-4acf0dcd724a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-02-13T00:36:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f23103ae-f519-4e9b-a553-d022dffff534
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T22:07:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afb178e5-68e2-4638-879e-008ac17efd37
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-04T22:07:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 896c52be-a449-445e-a3da-c861c9625988
            userCondition: null
            warning: null
            width: 50
        name: Attributes
        uid: f46d9bee-7fb1-40d5-a0c7-94ef4c375df1
        userCondition: null
    thumbFieldKey: null
handle: button
hasTitleField: true
icon: null
name: Button
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{buttonText}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{title ? title : 'Button: ' ~ button.label}"
