allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  a6fa0eb8-8bfb-4fa6-b2ed-cae575553c79:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:d33fff37-7dd3-40ba-91c0-926dace95c47'
      - 'layoutElement:4bde8a6a-e9be-4dfb-ad3e-8e2efd92a7f1'
    generatedFields:
      -
        handle: count
        name: Count
        template: '{cards|length} item(s)'
        uid: f9e09b42-05c1-4205-9527-eab289ec91de
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-09T23:20:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: 'Only shown in the admin.'
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 42a08e37-5175-42de-a309-fb9a6a90e8ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T20:40:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7ee19ba5-8919-4ba7-8a82-e84de143fc1f # Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f87729e-07ae-418c-ad4d-d73722ea51ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43097e6b-9127-42b7-9b31-a13f1a38ab46
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:10:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d33fff37-7dd3-40ba-91c0-926dace95c47
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-04T22:10:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bde8a6a-e9be-4dfb-ad3e-8e2efd92a7f1
            userCondition: null
            warning: null
            width: 50
        name: Attributes
        uid: d743dacc-20a6-4198-a8e8-f4b444006822
        userCondition: null
    thumbFieldKey: null
handle: cards
hasTitleField: true
icon: null
name: Cards
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{title ? title ~ ':' : ''} {count}"
