color: null
description: null
fieldLayouts:
  5ab6b9e3-b7ef-4120-ae08-a2d424aeef9d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T20:10:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d287c9b0-7a12-43f0-b428-24e36d2046e8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84bef64e-9bc3-4b66-bf57-9783c17ea20f
        userCondition: null
handle: cardTextBlock
hasTitleField: false
icon: null
name: 'Card Text Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: "{textBlock|striptags|truncate(50, '...')}"
titleTranslationKeyFormat: null
titleTranslationMethod: site
