allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3b76b405-719c-41c7-850d-7ec2a7ecac22:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:84603530-b7f2-4bc2-836b-b2c01c9bbb1a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-10T17:28:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55c62e14-e98e-4d1a-a181-845f6ebf20e4 # Heading
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9910e232-dc2d-4904-82ed-05abc657d403
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-28T19:51:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 75b94bea-4929-4bc5-8103-72bd8820c8c8 # Card Link
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84603530-b7f2-4bc2-836b-b2c01c9bbb1a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-10T17:29:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 486e0db8-6cbd-4cd7-85af-77040ab2b43c # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1abfa14f-d134-4de7-a026-c141c0b75c0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-10T17:29:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ca4c615-03a3-476a-be4f-78bcca88d6b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: decee093-ad21-4ef2-a706-7c96b2acdcb7
        userCondition: null
    thumbFieldKey: null
handle: card
hasTitleField: false
icon: null
name: Card
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{heading|striptags}'
