color: null
description: null
fieldLayouts:
  5d6a8266-367b-4242-ae74-023f9ad6f4e6:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:dabfc40b-ff1f-429d-ac37-c2607342ae8f'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-26T20:39:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4018390-9eaa-416b-a81c-bc7ddecf162c # Gallery Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dabfc40b-ff1f-429d-ac37-c2607342ae8f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b84c51fa-6760-42bd-8b0b-a5ec723e67c1
        userCondition: null
handle: galleryImage
hasTitleField: false
icon: null
name: 'Gallery Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
