allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  0ea174a2-617c-4d21-b4e7-3773d97a87b5:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:bb7b634f-5780-4144-89f9-8228402711da'
      - 'layoutElement:137144ce-7c7c-4cef-95e8-c737b79a007d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-26T20:21:06+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: "This block creates main banner image and content at the top of each page.  \r\nThere should only be one hero block per page."
            type: craft\fieldlayoutelements\Tip
            uid: 0b2b4481-2515-431a-b991-c35c2834fcc4
            userCondition: null
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 68c02e53-bd4b-45e6-8721-dfa278498dbb # Herobar Image
            handle: null
            instructions: null
            label: 'Herobar Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 137144ce-7c7c-4cef-95e8-c737b79a007d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2062b2bd-5662-4e7c-a7cf-0f05a4b4da60 # Herobar - Heading
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb7b634f-5780-4144-89f9-8228402711da
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 08c0e2a2-aaf5-48e9-bed6-e1f8fc7ce863 # Herobar - Subheading
            handle: null
            instructions: null
            label: Subheading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39e84ed4-dda3-4286-9858-da5a0bdf8766
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-06T16:10:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fde5281f-1a78-4749-abcc-3c136ffc0258 # Menu Link
            handle: heroButton
            instructions: null
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff9666ad-fe74-49b7-a0a4-f2e44564991d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b2e948bb-ce8f-4b37-b9e8-8c59de235b8d
        userCondition: null
    thumbFieldKey: 'layoutElement:137144ce-7c7c-4cef-95e8-c737b79a007d'
handle: hero
hasTitleField: false
icon: null
name: Hero
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
