allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  b6f4111d-fae4-4cc7-b336-9431bbc68d18:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-30T19:52:50+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Creates an easy series of repeatable blocks that include images and text side by side.'
            type: craft\fieldlayoutelements\Tip
            uid: 01631e60-5783-4a40-9549-eb62723da60a
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-30T23:17:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec61bdd4-80c7-488a-8173-6cc78a45f76a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T20:27:27+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 451ac180-f985-4b01-ba54-9b873058697b # Image Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 184fc152-4306-4533-9ae0-0d109499e78e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2c8cff48-7b66-47b2-beaf-b0956d2a3612
        userCondition: null
    thumbFieldKey: null
handle: imageBlocks
hasTitleField: true
icon: null
name: 'Image Blocks'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
