color: yellow
description: null
fieldLayouts:
  335cf2cd-41e8-4642-9df4-fc7a851807de:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T21:56:45+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Used grouping content for search engines and accessibility. Adds a semantic HTML <section> tag.'
            type: craft\fieldlayoutelements\Tip
            uid: 5932c1eb-9577-4c44-8ddc-c09edfe64b90
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T21:56:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: 'Only appears in admin'
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f53201a-b6b4-458b-88b4-9a15ea718e9b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d70bdcdd-80bd-4497-a977-4e8884471fc5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:24:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fd09047-3c8d-44e6-8ab7-44b1e19e8569
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T22:24:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5193d842-d12d-4b61-8524-6e3fa7994f79
            userCondition: null
            warning: null
            width: 100
        name: Attributes
        uid: efbc34b0-5845-469a-9ba3-04ede7768a18
        userCondition: null
handle: sectionStart
hasTitleField: true
icon: null
name: 'Section Start'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
