allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f9cb0c59-7cba-4b14-95b5-a97e840eb210:
    cardThumbAlignment: end
    cardView:
      - 'generatedField:17b1a5de-4412-4aa0-b6ac-3063c745d7d5'
    generatedFields:
      -
        handle: adminWidth
        name: Width
        template: 'Width: {blockWidth} / 12'
        uid: 17b1a5de-4412-4aa0-b6ac-3063c745d7d5
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-03T23:22:17+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 50ce781f-8f6e-4eeb-b0b7-faa9e9821913 # Text Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69e91706-6a35-43c5-aaa0-775077ee9a21
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39a605e3-f43e-445c-88f3-10909a05e15c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T18:49:27+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5f2efa0b-1e87-4d02-a636-f17256ef85d1 # Block Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 814e76fb-d534-4afe-9253-5d1c94d60693
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-03T23:22:17+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 95e5ecb2-f98f-455b-bd08-580743d5fa53 # Mobile Text Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09fc8b9e-3d2b-41dc-ae35-9b48887e7208
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-26T20:30:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6cdb288c-7205-4c21-9a0a-7d58451a4b56 # Vertical Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d44d530-681a-48c7-bc9e-6e2493a04805
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: 09db7656-ff1a-4af5-8d3c-7ce1b5ac5770
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T22:17:33+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d7f5b5cc-8e4d-422b-ba64-da1a79121801 # Classes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43a2eba1-aec5-4a29-a7d1-a5b1441597be
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-04T22:17:33+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09cd580c-e508-46a1-85a9-66581dd3a958 # Element ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 909a47f8-36df-4d6c-8c8f-1e7ca299baae
            userCondition: null
            warning: null
            width: 50
        name: Attributes
        uid: cb36922c-0f11-41b7-a065-62885d17a2d0
        userCondition: null
    thumbFieldKey: null
handle: textBlock
hasTitleField: false
icon: null
name: 'Text Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: "{textBlock|striptags|truncate(50, '...')}"
