color: null
description: null
fieldLayouts:
  178d2b2c-d5d8-4e43-8924-582180b94c86:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 053794be-63d9-4bcb-bdce-8452a3bf84b3 # Social Media - URLs - Facebook
            handle: null
            includeInCards: true
            instructions: null
            label: Facebook
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea33e848-e337-43bd-b951-64f48c541a9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ffb9b9ad-9374-470c-9e4a-cbed5212d7e6
        userCondition: null
handle: urls
hasTitleField: false
icon: null
name: URLs
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
