css: "@import url('/editorcss.php');"
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
js: "return {\r\n  toolbar: {\r\n      shouldNotGroupWhenFull: true\r\n  },\r\n\r\n  htmlSupport: {\r\n    allow: [\r\n        {\r\n            name: /.*/,\r\n            attributes: true,\r\n            classes: true,\r\n            styles: true\r\n        }\r\n    ]\r\n  },\r\n\r\n  alignment: {\r\n    options: [\r\n      'left',\r\n      'right',\r\n      'center',\r\n    ],\r\n  },\r\n\r\n  style: {\r\n    definitions: [\r\n      {\r\n        name: 'Red heading',\r\n        element: 'h2',\r\n        classes: [\r\n          'red-heading',\r\n        ],\r\n      },\r\n    ],\r\n  },\r\n\r\n  fontSize: {\r\n    options: [\r\n      'tiny',\r\n      'small',\r\n      'big',\r\n      'huge',\r\n    ],\r\n  }\r\n}"
name: Standard
toolbar:
  - style
  - heading
  - undo
  - redo
  - '|'
  - bold
  - italic
  - link
  - superscript
  - subscript
  - fontSize
  - '|'
  - fontColor
  - alignment
  - bulletedList
  - numberedList
  - '|'
  - insertImage
  - mediaEmbed
  - bookmark
  - removeFormat
  - sourceEditing
