headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  replaceTags:
    b: string
    i: em
toolbar:
  - undo
  - redo
  - '|'
  - bold
  - italic
  - link
  - superscript
  - subscript
  - fontColor
  - fontSize
  - '|'
  - bookmark
  - removeFormat
  - sourceEditing
