altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  e8b46e74-3faf-48ed-a914-c9e37f5cd7c7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T18:45:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 067cea37-d260-4378-ba32-387e6cd04181
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa0c5ab2-50b4-4581-825a-a1461104f0e4
        userCondition: null
    thumbFieldKey: null
fs: assets
handle: assets
name: Assets
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
