altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5e32e4ea-dbf2-46b8-8a34-af690a0f0bb6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-26T20:04:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3dce5a03-8eb7-4d38-bdf9-603de59d5fed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b1dbe40-0fb8-4dbb-bba5-acbc565d8159
        userCondition: null
fs: banners
handle: bannerImages
name: 'Banner Images'
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
