altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a68ab1ba-6a26-4ee1-8208-db2b6066f1db:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T18:45:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f9c3dc36-1ae3-4d14-b2b1-d431c5dac0e2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2026-02-10T17:35:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: ab9662c8-b04d-4f2e-ad42-3fa794f76773
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e12d42c1-c0bb-4ecc-8ff8-c5b6e3e0d33d
        userCondition: null
    thumbFieldKey: null
fs: blog
handle: blog
name: Blog
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transformed
transformSubpath: ''
