altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9850a42a-5da4-470b-a875-22d0800c0a2a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T18:45:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9e1f1a7f-32b7-4d51-908a-cf2249f3d0a4
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2026-02-10T17:37:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: e8482ec1-46d5-43ba-8f56-c2fb16087659
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 474fd4dc-4823-40e8-ae51-ef2e3527eb51
        userCondition: null
    thumbFieldKey: null
fs: ogImages
handle: ogImages
name: 'Sharing Images'
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transformed
transformSubpath: ''
