columnSuffix: null
handle: accordion
instructions: null
name: Accordion
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 72bf15bd-1c10-49b7-9d48-b1192343eea6 # Accordion Heading
    -
      __assoc__:
        -
          - uid
          - 41e7d3e7-7f22-4eec-8732-1a4b2cc13182 # Accordion Content
    -
      __assoc__:
        -
          - uid
          - 22bd92e8-fa46-4ac8-b91d-7b8a84bebccb # Accordion Icon
  includeTableView: false
  maxEntries: 3
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
