columnSuffix: null
handle: address
instructions: null
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: 150
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
