columnSuffix: null
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  createButtonLabel: 'Add block/element'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 75f7d82b-4d45-477b-848c-4f539cfe3469 # Hero
    -
      __assoc__:
        -
          - uid
          - fc3034e2-dcef-4781-b247-7e52cc007b39 # Heading
    -
      __assoc__:
        -
          - uid
          - 88653b5e-8ca3-4e44-85c0-6f158c9eca99 # Text Block
    -
      __assoc__:
        -
          - uid
          - 1dc47a8f-f250-4ac6-a46d-a8c63a0c6fd5 # Image
    -
      __assoc__:
        -
          - uid
          - 2a962a82-04dd-4e7a-9e92-e45cc7807082 # Image Blocks
    -
      __assoc__:
        -
          - uid
          - 6bd2bd9a-6b57-45fb-b914-f5b8e27e926f # Gallery
    -
      __assoc__:
        -
          - uid
          - b17a01c1-f13b-415b-80b2-c7e3680ec338 # Banner
    -
      __assoc__:
        -
          - uid
          - 52c2bd62-048d-4695-be78-f0110b0727de # Button
    -
      __assoc__:
        -
          - uid
          - 609f74fc-ee58-439b-afdb-10d9c919d562 # Cards
    -
      __assoc__:
        -
          - uid
          - 4deb1488-ff4e-4359-91ed-22574db39b8e # Accordion Wrapper
    -
      __assoc__:
        -
          - uid
          - 8f2af3e8-cdf5-4c6b-921e-814f25286901 # Contact Form
    -
      __assoc__:
        -
          - uid
          - c88e53c0-b0e2-4f2e-8b79-69954becb0f7 # Video
    -
      __assoc__:
        -
          - uid
          - 5806aa3f-0845-4297-a1c8-edc07c16ef07 # Section Start
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
