columnSuffix: null
handle: email
instructions: null
name: Email
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
