columnSuffix: null
handle: gallery
instructions: null
name: Images
searchable: false
settings:
  createButtonLabel: 'Add Image'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 70722bde-7efe-42d4-a06e-399a44b02435 # Gallery Image
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
