columnSuffix: null
handle: imageAspectRatio
instructions: null
name: 'Image Orientation'
searchable: false
settings:
  customOptions: false
  iconsOnly: true
  options:
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - icon
          - square
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Portrait/Tall
        -
          - value
          - tall
        -
          - icon
          - rectangle-vertical
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Landscape/Wide
        -
          - value
          - wide
        -
          - icon
          - rectangle-wide
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Custom
        -
          - value
          - custom
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
