columnSuffix: null
handle: label
instructions: null
name: Label
searchable: false
settings:
  byteLimit: null
  charLimit: 15
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
