columnSuffix: null
handle: menuHeader
instructions: null
name: 'Header Menu'
searchable: false
settings:
  createButtonLabel: 'Add item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - fc8b81be-d376-4af1-9eef-ec1d2ae8e3f0 # Menu Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
