columnSuffix: null
handle: menuFooter
instructions: null
name: 'Footer Menu'
searchable: false
settings:
  createButtonLabel: 'Add item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - f02cfe8f-517a-4f23-a3bd-3ed65dc87db9 # Menu Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
