columnSuffix: null
handle: phoneNumber
instructions: null
name: 'Phone Number'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  types:
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
