columnSuffix: null
handle: platform
instructions: null
name: Platform
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Facebook
        -
          - value
          - facebook
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'X (Twitter)'
        -
          - value
          - xTwitter
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Instagram
        -
          - value
          - instagram
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LinkedIn
        -
          - value
          - linkedin
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
