columnSuffix: null
handle: socialMedia
instructions: "Set the links to social media platforms. These will be used throughout the site where they are linked to within the design. It won't update links entered within content blocks."
name: 'Social Media'
searchable: false
settings:
  createButtonLabel: 'Add platform'
  defaultIndexViewMode: cards
  enableVersioning: true
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 8e90774b-6fbc-4e14-b5ee-0e7072719820 # Social Medial URL
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
