columnSuffix: eqxpofhf
handle: textAlignCenter
instructions: 'Turning this field on will align text center on mobile sized screens.'
name: 'Mobile Text Alignment'
searchable: false
settings:
  default: false
  offLabel: 'Text Align Left (On Mobile)'
  onLabel: 'Text Align Center (On Mobile)'
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
