columnSuffix: ozsdthxd
handle: uppercase
instructions: null
name: Uppercase
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
