columnSuffix: null
handle: verticalAlignCenter
instructions: 'When activated aligns text or items vertically centered'
name: 'Vertical Alignment'
searchable: false
settings:
  default: false
  offLabel: Top
  onLabel: Center
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
