columnSuffix: kuaiidjs
handle: video
instructions: 'Paste the embed/iframe URL.'
name: Video
searchable: false
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
