fieldLayouts:
  1dcb4f06-bb55-4342-9765-5b0c2621afc5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-06T18:15:04+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ec34d844-46a7-4389-965e-a1a4048a0798 # Header Menu
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5698c97-4c3e-45c0-aebf-25562515b717
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-06T18:15:04+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fde5281f-1a78-4749-abcc-3c136ffc0258 # Menu Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 977fb3bb-6973-47fe-a881-d21097ab46a6
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 0c62eee9-b31e-4da3-8942-2a50eebfb813
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-02-06T18:15:04+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b7e52fb1-8f8c-42af-b4dd-89f7bff35de2 # Footer Menu
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2720e589-5482-4771-9797-dd19dc6c057a
            userCondition: null
            warning: null
            width: 100
        name: Footer
        uid: f276bf44-0565-45d9-9cee-f80ff79f18c2
        userCondition: null
    thumbFieldKey: null
handle: menus
name: Menus
sortOrder: 2
