fieldLayouts:
  9e790d65-95f2-44bb-8135-327e7f77b6aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 64a1d559-0f30-491d-92c9-177cf340853c # Company Name
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 930c2e06-ec65-4ff3-b619-746204f9ac12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-06T19:04:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8e6c61b-4a37-4d1a-8de1-c908b52dbf43 # Phone Numbers
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88d5fb63-c15c-496c-9d1a-3462d7c1c32c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-06T03:03:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8a21b25b-dfd1-4441-8276-d1457d126775 # Email
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66bb7e05-758f-4848-b3d7-6fb22c3cb1d7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-06T19:04:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bf74653-4a17-4c76-9fa3-4a5d76c42703 # Address
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7126713-4349-4106-9828-4ff3fef9201f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-02-06T19:04:48+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 602c4974-25ab-4f0f-bf26-09a60494c2aa # Directions Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 641d0ced-cac9-44ff-952f-a831fe1b4d75
            userCondition: null
            warning: null
            width: 50
        name: Globals
        uid: 4036473b-47dd-48fd-bfc5-5dda56b5abce
        userCondition: null
    thumbFieldKey: null
handle: siteInformation
name: 'Site Information'
sortOrder: 1
