fieldLayouts:
  9e790d65-95f2-44bb-8135-327e7f77b6aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T18:45:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 64a1d559-0f30-491d-92c9-177cf340853c # Company Name
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 930c2e06-ec65-4ff3-b619-746204f9ac12
            userCondition: null
            warning: null
            width: 100
        name: Globals
        uid: 4036473b-47dd-48fd-bfc5-5dda56b5abce
        userCondition: null
handle: siteInformation
name: 'Site Information'
sortOrder: 2
