defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 554d5c17-904d-4637-9bfc-f85a9f70ba44 # Page Blocks
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  42773db2-f2e9-40a9-ab5e-e3406f1a6a25: # XM Craft Starter
    enabledByDefault: true
    hasUrls: true
    template: _default.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: b262d4aa-7d0b-43e8-b91a-f15def8b1785
type: structure
