cardThumbAlignment: end
cardView:
  - 'layoutElement:138dd9ea-9e35-4ff6-b65c-82ceb811ffbe'
tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-10T16:48:28+00:00'
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        required: true
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 8ce9c78a-6a55-4b72-a238-18ad7b1c36b8
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2024-12-10T16:48:28+00:00'
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: c1ff2870-84e0-4060-b002-8e55e7f624f7
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-10T16:48:28+00:00'
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 138dd9ea-9e35-4ff6-b65c-82ceb811ffbe
        userCondition: null
        warning: null
    name: Content
    uid: 945a2920-1ecd-4d3f-8a6f-d8e2c64dd7a8
    userCondition: null
thumbFieldKey: null
